[package]
name = "rust-runner"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
winapi = { version = "0.3", features = ["winuser", "libloaderapi", "winnt"] }

# Enable optimizations for better evasion
[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
